# Generated by Django 5.2.6 on 2025-10-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_mahasiswa_angkatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='angkatan',
            field=models.IntegerField(),
        ),
    ]
